spring:
  application:
    name: Spring Boot "Clean" Project Structure
  datasource:
    name: H2 Connection
    url: jdbc:h2:mem:cleanarch
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate.jdbc.batch_size: 10
      hibernate.order_inserts: true
      hibernate.generate_statistics: true